server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://database:5432/testdb
    username: postgres
    password: p0stgr@s
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true

security:
  oauth2:
    resource:
      user-info-uri: http://authserver:8901/auth/user

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com.example: DEBUG